FROM navitia/ruspell as ruspell
FROM navitia/navitia_model as navitia_model
FROM tartare_functional_tests

COPY --from=ruspell /app/ruspell /usr/src/app/bin/ruspell
COPY --from=navitia_model /app/gtfs2ntfs /usr/src/app/bin/gtfs2ntfs

