ARG TAG=master
FROM navitia/ruspell as ruspell
FROM navitia/navitia_model as navitia_model

FROM navitia/tartare:${TAG}
USER root
RUN apk --update add aspell aspell-fr && rm -rf /var/apk/cache/
USER tartare

COPY --from=ruspell /app/ruspell /usr/src/app/bin/ruspell
COPY --from=navitia_model /app/gtfs2ntfs /usr/src/app/bin/gtfs2ntfs
