FROM par-vm221.srv.canaltp.fr:5000/ruspell as ruspell
FROM par-vm221.srv.canaltp.fr:5000/navitia_model as navitia_model
FROM tartare_functional_tests

USER root
RUN apk --update add aspell aspell-fr && rm -rf /var/apk/cache/
USER tartare
COPY --from=ruspell /app/ruspell /usr/src/app/bin/ruspell
COPY --from=navitia_model /app/gtfs2ntfs /usr/src/app/bin/gtfs2ntfs

