ARG TAG=master
FROM par-vm221.srv.canaltp.fr:5000/ruspell as ruspell


FROM par-vm221.srv.canaltp.fr:5000/tartare:${TAG}
COPY --from=ruspell /app/ruspell /usr/src/app/bin/ruspell

CMD ["celery", "-A", "tartare.tasks.celery", "worker", "-Q", "process_ruspell"]
