version: '2'

services:
  tartare_worker:
    image: tartare_functional_tests
    environment:
      - RETRY_NUMBER_WHEN_FAILED_TASK=0
      - TARTARE_RABBITMQ_HOST=amqp://guest:guest@rabbitmq:5672//
      - MONGO_URI=mongodb://mongo-server/tartare?connect=false
    command: celery -A tartare.tasks.celery worker -Q tartare
    links:
      - rabbitmq
      - mongo-server
    depends_on:
      - rabbitmq

  ruspell_worker:
    image: tartare_ruspell_functional_tests
    environment:
      - TARTARE_RABBITMQ_HOST=amqp://guest:guest@rabbitmq:5672//
      - MONGO_URI=mongodb://mongo-server/tartare?connect=false
    command: celery -A tartare.tasks worker -Q process_ruspell
    links:
      - rabbitmq
      - mongo-server
    depends_on:
      - rabbitmq

  tartare_beat:
    image: tartare_functional_tests
    environment:
      - TARTARE_RABBITMQ_HOST=amqp://guest:guest@rabbitmq:5672//
    command: celery -A tartare.tasks.celery beat
    links:
      - rabbitmq

  tartare_webservice:
    image: tartare_functional_tests
    environment:
      - TARTARE_RABBITMQ_HOST=amqp://guest:guest@rabbitmq:5672//
      - MONGO_URI=mongodb://mongo-server/tartare?connect=false
    command: uwsgi --mount /=tartare:app --http 0.0.0.0:5666 --wsgi-disable-file-wrapper --add-header Access-Control-Allow-Origin:*
    links:
      - rabbitmq
      - mongo-server

  mongo-server:
    image: mongo

  rabbitmq:
    image: rabbitmq:management

  http_download_server:
    image: visity/webdav
